openapi: 3.0.0
info: 
  title: Image Quality Assessment by Ainize
  version: 0.1.1

servers: 
  - url: https://evaluate-image.ehdgus8077.endpoint.ainize.ai

paths:
  /eval/images:
    post:
      summary: Returns a score of image.
      parameters:
        - name: urlList
          in: query
          required: true
          schema:
            items:
              type: array
      responses:
        '200':
          description: A score of image.
          content:
            applicatioin/json:
              schema:
                type: object
                properties:
                  score:
                    type: number
        default:
          description: Unexpected error 
  /eval/image:
    get:
      summary: Returns a score of Image and Image.
      parameters:
        - name: url
          in: query
          required: true
          schema:
            items:
              type: string
      responses:
        '200': 
          description: OK
