openapi: 3.0.0
info: 
  title: Image Quality Assessment by Ainize
  version: 0.1.1

servers: 
  - url: https://evaluate-image.ehdgus8077.endpoint.ainize.ai

paths:
  /healthz:
    get:
      summary: API For health checking.
      responses:
        '200':
          description: OK
  /eval/images:
    post:
      summary: Returns a score of Image and Image.
      requestBody:
        required: true
        content:
            applicatioin/json:
              schema:
                type: object
                properties:
                  urlList:
                    type: array
                    items:
                      type: string
                      example: <image path>
            
      responses:
        '200':
          description: A score of image.
          content:
            applicatioin/json:
              schema:
                type: object
                properties:
                  score:
                    type: array
                    items:
                      type: number
                      example: 5.6666
  /eval/image:
    get:
      summary: Returns a score of Image and Image.
      parameters:
        - name: url
          in: query
          required: true
          schema:
            items:
              type: string
      responses:
        '200': 
          description: OK
