openapi: 3.0.0
info: 
  title: Image Quality Assessment by Ainize
  version: 0.1.1

servers: 
  - url: https://endpoint.ainize.ai/hyunhyerim/wonny/

paths:
  /evaluate:
    get:
      summary: Returns a score of image.
      parameters:
        - name: image
          in: query
          required: true
          allowReserved: true
          schema:
            type: string
      responses:
        '200': # status code
          description: A score of image.
          content:
            applicatioin/json:
              schema:
                type: object
                properties:
                  score:
                    type: number
        '400':
          description: The image path is invalid.
        default:
          description: Unexpected error 
                