openapi: 3.0.0
info: 
  title: Image Quality Assessment by Ainize
  version: 0.1.1

servers: 
  - url: https://evaluate-image.ehdgus8077.endpoint.ainize.ai

paths:
  /eval:
    get:
      summary: Returns a score of image.
      parameters:
        - name: filePathList
          in: query
          required: true
          allowReserved: true
          schema:
            type: array
      responses:
        '200': # status code
          description: A score of image.
          content:
            applicatioin/json:
              schema:
                type: object
                properties:
                  score:
                    type: number
        default:
          description: Unexpected error 
                