openapi: 3.0.0
info: 
  title: Image Quality Assessment by Ainize
  version: 0.1.1

servers: 
  - url: https://wonny.ehdgus8077.endpoint.ainize.ai

paths:
  /healthz:
    get:
      summary: API For health checking.
      responses:
        '200':
          description: OK
  /eval/image:
    get:
      summary: Returns a score of Image and Image.
      parameters:
        - name: url
          in: query
          required: true
          schema:
            items:
              type: string
          examples:
            sample:
              summary: sample URL
              value: 'https://drive.google.com/uc?export=view&id=1SjpQKWR2ssWU358bI_d9YuFSxoNU1WPZ'   # ?ids=5
      responses:
        '200': 
          description: OK
