openapi: 3.0.0
info: 
  title: Image Quality Assessment by Ainize
  version: 0.1.1

servers: 
  - url: https://endpoint.ainize.ai/donghyeon/wonny/

paths:
  /evaluate:
    get:
      summary: Returns a score of image.
      parameters:
        - name: filePath
          in: query
          required: false
          allowReserved: true
          schema:
            type: string
        - name: filePathList
            in: query
            required: false
            allowReserved: true
            schema:
              type: array
      responses:
        '200': # status code
          description: A score of image.
          content:
            applicatioin/json:
              schema:
                type: object
                properties:
                  score:
                    type: number
        default:
          description: Unexpected error 
                